### ISSUE TITLE
Composer installation lacks backend controller

### ISSUE THREAD

**Issue by JoshuaBehrens** [FriendsOfShopware/FroshEnvironmentNotice#3]
If installed via composer there are errors in the backend controller as the template is not build.

## Actual behaviour

The current plugin expects the backend template to be compiled via npm befure being usable.

## Expected behaviour

One can simply install by composer and the backend template gets rendered by npm automatically

OR

there is no need for npm while keeping the advantages in a reasonable amount.

## Steps to reproduce

1. Install the plugin via git or composer
2. Do not execute npm

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshEnvironmentNotice/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by dneustadt** [comment]
See the [extjs](https://github.com/FriendsOfShopware/FroshEnvironmentNotice/tree/extjs) branch featuring a native extjs app. Since there is no need to build assets with a native app there will always be a app.js present no matter the deployment method.

**Comment by JoshuaBehrens** [comment]
I will look at this as soon as possible. Thanks so far for the extjs contribution I could never serve.

**Comment by JoshuaBehrens** [comment]
Woops I accidently closed it

**Comment by JoshuaBehrens** [comment]
Looks good, works as expected. :+1:
